### ISSUE TITLE
Could you please show example code of stream ?

### ISSUE THREAD

**Issue by kim257** [sirrodgepodge/morgan-body#17]
I don't understand , I want to log to file 

> stream: (default: null), optionally provide a stream (or any object of the shape { write: <Function> }) to be used instead of "process.stdout" for logging to,

How to do that  ?

**Comment by sirrodgepodge** [comment]
sorry, hectic times on my end so I don't have time to double check this code for you but should be:

```js
import morganBody from 'morgan-body';
import express from 'express';
import bodyParser from 'body-parser';

const app = express();

// must parse body before morganBody as body will be logged
app.use(bodyParser.json());

// hook morganBody to express app
morganBody(app, {
  stream: {
    write: function warnInsteadOfLog(messageStr) {
      console.warn(messageStr);
    }
  }
});
```

Let me know if that works!

**Comment by sirrodgepodge** [comment]
btw, just saw that you're doing tech in Thailand, so so cool! :)

**Comment by kim257** [comment]
Ah it's work you save my life :) thank you so much, But how did you know about me :) ?
one question can I log request header also ?

**Comment by sirrodgepodge** [comment]
great!

I actually saw your name on your profile and Googled it because I could not figure out where it was from :)

So this guy opened a pull request last week:
https://github.com/sirrodgepodge/morgan-body/pull/16

I have not had time to review it yet, perhaps you could use the code in his branch?  You could also write tests so I can merge it but I don't want to put that burden on you.

**Comment by sirrodgepodge** [comment]
ah gotcha, wait so will prettify: false solve what you need?

**Comment by kim257** [comment]
Sorry for reply late, solved it

![image](https://user-images.githubusercontent.com/16816483/50475656-1035a000-09f8-11e9-870e-945895633fec.png)

thank you `:)
